### ISSUE TITLE
Roadchoice Search Bug

### ISSUE THREAD

**Issue by AsmitKMishra** [aemsites/vg-roadchoice-com#103]
### Issue Type

Bug

### Summary

Offset does not reset to 0 when clicking on category.

### Priority

Blocker

### Description

The offset maintaining the pagination of results does not reset when clicking on any category causing issues with search results.

### Affected Device Classes

Desktop

### Affected Browsers/Devices and Versions

Chrome

### Steps to Reproduce

1. Navigate to https://www.roadchoice.com/
2. Search by either cross reference or part number eg: https://www.roadchoice.com/search/?q=900&st=cross&offset=0
3. Click on show more at least once and notice the offset change in the URL
4. Now click on any category, preferably any category with less products than being displayed currently. eg: https://www.roadchoice.com/search/?q=900&st=cross&offset=1&category=air+coils+and+components
5. Observe how the offset value still remains same in the URL and in case of category having less products there is no result displayed due to offset not being reset to 0.

### Expected Results

***

### Actual Results

<img width="959" alt="Screenshot 2024-12-04 192323" src="https://github.com/user-attachments/assets/ffd82eb7-d109-4116-99db-a78ea3ae9811">
<img width="960" alt="Screenshot 2024-12-04 192448" src="https://github.com/user-attachments/assets/d62bed11-9086-4326-ab62-8ff6177e7cc4">

**Comment by BeckyMedlin** [comment]
@cincplug Please coordinate a hotfix with @alexiscoelho for this bug.

**Comment by cincplug** [comment]
@AsmitKMishra Should be fixed, please test on
https://103-hotfix-opensearch--vg-roadchoice-com--volvogroup.aem.page/

**Comment by AsmitKMishra** [comment]
Testing Completed. Offset resets to 0 when going to category, which allows search to work as expected.

**Comment by cincplug** [comment]
Merged to production, @AsmitKMishra you can recheck it in production, I checked it and it works
