### ISSUE TITLE
Bug: Medium: WinOS/MacOS + Firefox : Unable to see the Catergories menu although clicked on it 

### ISSUE THREAD

**Issue by girishdigrajkar** [aemsites/vg-roadchoice-com#39]
**Steps:**
1. On WinOS/MacOS  open Firefox browser
2. Navigate to https://main--vg-roadchoice-com--hlxsites.hlx.page/
3. Click on Categories menu and validate

**Expected vs Actual:**
The Categories menu does not expand although clicked on Categories menu

MacOS:
![image](https://github.com/aemsites/vg-roadchoice-com/assets/125972657/3189d778-2502-4d4c-a97e-d686f77e22cb)

WinOS:
![image](https://github.com/aemsites/vg-roadchoice-com/assets/125972657/e20c2e8c-7a27-48b2-a61a-14c9904a106c)

**Comment by jonatan-lledo-netcentric** [comment]
this issue is already fixed and can be closed
