### ISSUE TITLE
NFR: Analyze JSON parts files structure

### ISSUE THREAD

**Issue by urtzi-sotes** [aemsites/vg-roadchoice-com#42]
### Context/Description

Currently, there are three JSON files (cr-data.json, road-choice-make-model-part-filter-options.json, and road-choice-website-images.json) are loaded from three different Excel files stored in the Adobe SharePoint:

- [cr-data](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B0B5D9BEA-6C70-42C4-855B-DC2478188C83%7D&file=cr-data.xlsx&action=default&mobileredirect=true)
- [road-choice-make-model-part-filter-options](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BE01F318F-2EAE-4817-AE9C-CD903CCB3217%7D&file=road-choice-make-model-part-filter-options.xlsx&action=default&mobileredirect=true)
- [road-choice-website-images](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B0C890F39-4BEF-4614-AF93-D478AA285F3B%7D&file=road-choice-website-images.xlsx&action=default&mobileredirect=true)

We need to analyze them to define the OpenSearch index and create the OpenSearch documents.

### Acceptance Criteria

**Non-functional AC:** 
- JSON files analyzed.
- Analysis documented in the Wiki.

**Comment by urtzi-sotes** [comment]
It is documented [here](https://projects.netcentric.biz/wiki/display/VOLVOFN/OSRC%3A+Data+Analysis)

**Comment by ZoeBeykirch** [comment]
Closing now that research into JSON part file structure is completed and documented above.
