### ISSUE TITLE
FR: [Ingestion] - Define & create: OpenSearch index structure (1 of 6)

### ISSUE THREAD

**Issue by urtzi-sotes** [aemsites/vg-roadchoice-com#43]
### Context/Description

We need to define the OpenSearch Index's structure able to include all the existing parts information.

### Acceptance Criteria

- Index structure defined
- Index structure documented in the Wiki

**Comment by urtzi-sotes** [comment]
Index structure documented [here](https://projects.netcentric.biz/wiki/display/VOLVOFN/OSRC%3A+Index+Definition)

**Comment by AsmitKMishra** [comment]
<img width="762" alt="001" src="https://github.com/user-attachments/assets/a28c9d7b-96f9-43dd-b4f8-60fdccb33b1f">
part category belongs to two JSON field. but has only one mentioned.
cr-data.json should also be included.

**Comment by AsmitKMishra** [comment]
Above issue is fixed now.
<img width="706" alt="Screenshot 2024-10-15 112158" src="https://github.com/user-attachments/assets/39240da0-6551-4d41-a7e3-848f10197faa">

**Comment by ZoeBeykirch** [comment]
Closing this ticket, and the deployment will be taken up in another ticket
