### ISSUE TITLE
FR: [Ingestion] - Develop Data Process Lambda function (2 of 6)

### ISSUE THREAD

**Issue by urtzi-sotes** [aemsites/vg-roadchoice-com#44]
### Context/Description

We need to do the initial ingestion of the OpenSearch documents and update them every time any part is added, updated, or deleted.
Every time this occurs a repository_dispatch event is sent to the repository which will be handled by a GitHub action that will initially trigger this lambda. It is in charge of processing the parts' files and transforming them into OpenSearch documents. As a result, the documents are stored in an S3 bucket.

In a later phase, we will configure a Queue service to manage events asynchronously.

### Acceptance Criteria

- Lambda to download JSON part files and create OpenSearch Documents implemented:
  - The lambda will read the public JSON part files and convert them into OpenSearch Documents.
  - The OpenSearch Documents will be stored in a specific S3 bucket and will be ingested later on (#65).
- GitHub action event defined.
- The trigger event is the one sent by the GitHub action
- Logs enabled
- Unit tests created. (if needed)
- Lambda building included in the CI/CD pipeline.
- Everything is documented in the wiki space.

**Comment by BeckyMedlin** [comment]
Testing needs to be completed in #61 per discussion on 10/18/2024.
