### ISSUE TITLE
NFR: Analyze Existing Search Functionality

### ISSUE THREAD

**Issue by urtzi-sotes** [aemsites/vg-roadchoice-com#46]
### Context/Description

Currently, The [Road Choice website](https://www.roadchoice.com/) has two searches: Cross-reference and Part Number.

We need to analyze them to define in order to create the OpenSearch documents

### Acceptance Criteria

**Non-functional AC:**
- Analyze all the functionalities of the different searches.
- Search queries documented in the wiki.

**Comment by urtzi-sotes** [comment]
This is documented [here](https://projects.netcentric.biz/wiki/display/VOLVOFN/OSRC%3A+All+Search+Solution+Analysis)

**Comment by ZoeBeykirch** [comment]
Closing now that research into existing search functionality is completed and documented above.
