### ISSUE TITLE
FR: [Query] - GraphQL API Cross-reference Search (1 of 4)

### ISSUE THREAD

**Issue by urtzi-sotes** [aemsites/vg-roadchoice-com#47]
### Context/Description

The search interface is exposed to the Front end by means of a GraphQL endpoint that performs the actual OpenSearch query and returns the results in an understandable format for the front end.

### Acceptance Criteria

- Create a new GraphQL search endpoint for the Cross-reference search (`rccrossreferencesearch`) in the test-eds environment:
  - [https://search-api-qa-eds.aws.43636.vnonprod.com/search](https://search-api-qa-eds.aws.43636.vnonprod.com/search)
- The endpoint must use the `cr_search_query_template` search template.
- The search results can be paginated .
- The OpenSearch results must be formatted in an easy-to-understand manner for the front end.
- Document in the [wiki](https://projects.netcentric.biz/wiki/display/VOLVOFN/Search%3A+Cross-Reference+Search+Query)

**Comment by BeckyMedlin** [comment]
@palmajano Please update this ticket with details. Thank you.

**Comment by urtzi-sotes** [comment]
GraphQL API for Cross-reference search documented [here](https://projects.netcentric.biz/wiki/display/VOLVOFN/Search%3A+Cross-Reference+Search+Query)

**Comment by AsmitKMishra** [comment]
Testing Completed. Feature meets the acceptance criteria.
Search results are formatted and paginated.

**Comment by AsmitKMishra** [comment]
Closing the ticket as deployment will be held in another ticket.
