### ISSUE TITLE
FR: [Query] - Create OpenSearch Templates for P/N and Cross-reference Searches

### ISSUE THREAD

**Issue by urtzi-sotes** [aemsites/vg-roadchoice-com#48]
### Context/Description

We need to define the OpenSearch templates' structure to include all the functionalities of the previously defined searches.

### Acceptance Criteria

- 4 Search templates defined 
- Search templates documented in the wiki

**Comment by urtzi-sotes** [comment]
search queries definition [here](https://projects.netcentric.biz/wiki/display/VOLVOFN/OSRC%3A+Search+Queries)

**Comment by ZoeBeykirch** [comment]
Closing ticket and deployment will be taken up in another ticket.
