### ISSUE TITLE
FR: [Ingestion] - Deploy OpenSearch Index Update Lambda function via Terraform (5 of 6)

### ISSUE THREAD

**Issue by palmajano** [aemsites/vg-roadchoice-com#66]
### Context/Description

We use Terraform tool to automatically deploy the AWS infrastructure in the CICD pipeline.

### Acceptance Criteria

- Terraform code to deploy the lambda in #65 created.
- The lambda is triggered when a new file containing OpenSearch documents has been created in the specific S3 bucket.
- Logs enabled.
- Lambda Permission to List, Get and Delete objects in the S3 bucket.
- Lambda Permission to bulk feed documents into the RoadChoice index.
- Lambda permissions to be triggered by the S3 bucket.
- Set concurrent executions to 1.
- Lambda deployment included in the CI/CD pipeline.
- Everything is documented in the wiki space.
- Test the lambda function implemented in ticket #65

**Comment by urtzi-sotes** [comment]
Lambda function implemented in ticket #65 tested in qa-eds environment.

End to end testing done of the two lambdas implemented in #61 and #65 and everything works as expected:
- Parts information downloaded and stored in s3 bucket.
- OS documents uploaded to the new OS index version.
- s3 file deleted from s3 bucket

**Comment by urtzi-sotes** [comment]
Full testing has been done from my side.
