### ISSUE TITLE
FR: [Deployment] - Ingestion Pipeline Production Deployment (1 of 3)

### ISSUE THREAD

**Issue by palmajano** [aemsites/vg-roadchoice-com#71]
### Context/Description

The are 6 tickets that implement the ingestion pipeline: #43 #44 #61 #65 #66 #45.
Once all of them are deployed to QA and tested, the ingestion pipeline must be deployed and tested on Production.

### Acceptance Criteria

- Ingestion Pipeline is deployed to Production via Pull Request.
- The GitHub action is deployed to production.
- Every time a part file is published, the pipeline is triggered.
- As a result, the OpenSearch index is updated and:
  - new products are searchable.
  - deleted products are no longer searchable.
  - updated products contain the updated values.

**Comment by urtzi-sotes** [comment]
Tickets -> #43 #44 #61 #65 #66 Deployed to production.

This ticket will be closed once #45 is deployed to production.

**Comment by urtzi-sotes** [comment]
Ticket #45 has been deployed and the ingestion pipeline has been end-to-end tested and works as expected.

I close this deployment ticket.

Backend work has been finished and everything is deployed to production.
